name: Deploy to Server

on:
  push:
    branches:
      - develop  # develop 브랜치에 push 될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/kkultrip  # 서버에서 프로젝트 폴더로 이동
          git pull origin develop  # 최신 코드 가져오기
          npm install  # 의존성 설치
          npm run build  # 프로젝트 빌드
          nohup npm run start &  # 백그라운드에서 서버 실행
          EOF

